### ISSUE TITLE
[Bugs] Test Cases

### ISSUE THREAD

**Issue by ArthDh** [rushtheboy/ECE143_Drug_Analysis#2]
1) Grid Search: 
m = 5
n = 4
blocks = [(0,0)]
assert 0 == count_paths(m, n, blocks)

is not a valid case since the source can not be blocked.
Same for the next test case.

2) Next Permutation:
t = (1)
assert (1) == next_permutation(t)

type(t) will be considered as an int not a tuple, hence the assertion will fail. You should have used something like t=(1,)

Great job on the remaining test cases! :+1: 

Can the person who wrote the final test case for Convex Cover email me their solution? The test is very interesting.

Best of luck :D

**Comment by ElegantLin** [comment]
OK. We will change these cases and write a test case for Convex Cover.

Thanks

**Comment by ArthDh** [comment]
Ah no, I meant the test case was good I wanted to check how you approached the problem!

**Comment by BinahHu** [comment]
> OK. We will change these cases and write a test case for Convex Cover.
> 
> Thanks

Hi TA, for the convex cover test case, actually we use the flawed algorithm proposed by another TA on piazza and can not pass the proposed test case. But we believe the proposed test case is a very interesting counterexample for that algorithm

**Comment by ArthDh** [comment]
Yes, I agree with you that it was a very nicely done counterexample. Was wondering if any of yours algorithm passed the test case? If so would they mind sharing their solution?

**Comment by BinahHu** [comment]
To my best knowledge, none of our algorithms can pass the test case. To pass this case, I can only think of brute force algorithm. Actually I guess the original problem (if without convex constrain) is a NPC problem. But I am not sure how to utilized the convex constrain.

**Comment by ArthDh** [comment]
I see, well Great job anyways and wish you all best of luck for future endeavors! :)
